# Site settings
title: Landon Waters Personal Portfolio
description: A personal webpage hosted by Github for Landon Waters. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://ljwaters.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Landon Waters
user_description: Landon Waters is a graduate student at Willamette University studying Data Science. He got his undergrad in Economics and Data Science, minoring in Mathematics. He played varsity football for four years for the Willamette Bearcats.
user_title: Data Analyst
email: ljwaters@willamette.edu
# twitter_username: lorem_ipsum
github_username:  ljwaters
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
