# Site settings
title: Landon Waters' Personal Portfolio
description: A personal webpage hosted by Github for Landon Waters. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://ljwaters.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Landon Waters
user_description: |
  I found my way into data science through sports. As a lifelong athlete, I’ve always been curious about what makes a team thrive; how does leadership, chemistry, and the numbers behind the scenes come together to shape outcomes? That curiosity eventually led me to the world of data.

  I started studying economics mostly to check a box, but I quickly realized its power for explaining how systems work. More importantly, how they can be changed for the better. It clicked for me that data science and economics together could be a bridge: using technical skills to bring real human insight to big questions.

  I’m now looking for data analyst roles where I can use R, Python, SQL, and Excel to do more than optimize profit. I want to find meaningful patterns, surface overlooked impacts, and help drive decisions that actually improve people’s lives.

  Growing up in a small town surrounded by small businesses, I’ve seen how policy and corporate decisions play out in the real world. Community isn’t built around a big-box store, it’s built around the local coffee shop, the barber, the grocery store on the corner.

  My goal is to join teams that ask tough questions, use data to uncover what’s hidden, and seek solutions that value people as much as profit. Whether it’s in sports analytics, public policy, or purpose-driven business, I want to help organizations see what the numbers are really saying and use that insight to create positive change.

user_title: Data Scientist
email: ljwaters@willamette.edu
github_username:  ljwaters

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
